type Product {
  name: String!
  updatedAt: Time
  description: String
  tags: [String]
  price: Int!
  productLink: String
  productType: String
  brand: String!
  rating: Int
  createdAt: Time
  category: String
  imageLink: String
}